server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456

  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: lyq765@aliyun.com
    password: a2862465

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"

emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.229.128:3000/create_face_model
    checkinUrl: http://192.168.229.128:3000/checkin
  email:
    system: lyq765@aliyun.com
    hr: 1325084702@qq.com
  image-folder: D:\IDEA2020\Workspace\project\img
  code: F4BCE38169006745
  recieveNotify: http://192.168.5.100:8080/emos-wx-api/meeting/recieveNotify
  url: http://118.25.251.70:9090/emos-workflow

wx:
  app-id: wxf3e10f6f08080a46
  app-secret: 44bdfc4a3252e396a20121d47e44a959







